on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy to
        required: true
        type: choice
        default: development
        options:
        - development
        - test
        - production
        - preproduction

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to AWS
    steps:
      - name: terraform validation
        run: |
          echo "selected environment is : make  ${{ inputs.environment }}" terraform-apply
